spring:
  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate.ddl-auto: update
    database: mysql
    show-sql: true
    properties.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/wootecobook?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: zzinbros
    password: 1234

debug: true
